.lf 1 ./man/man5/srec_needham.5
'\" t
.\"     srecord - manipulate eprom load files
.\"     Copyright (C) 2003, 2006-2009 Peter Miller
.\"
.\"     This program is free software; you can redistribute it and/or modify
.\"     it under the terms of the GNU General Public License as published by
.\"     the Free Software Foundation; either version 3 of the License, or
.\"     (at your option) any later version.
.\"
.\"     This program is distributed in the hope that it will be useful,
.\"     but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"     GNU General Public License for more details.
.\"
.\"     You should have received a copy of the GNU General Public License
.\"     along with this program. If not, see
.\"     <http://www.gnu.org/licenses/>.
.\"
.ds n) srec_needham
.TH \*(n) 5 SRecord "Reference Manual"
.SH NAME
srec_needham \- Needham EMP\[hy]series programmer ASCII file format
.if require_index \{
.\}
.SH DESCRIPTION
This format is understood by Needham Electronics' EMP\[hy]series programmers.
See \f[CW]www.needhams.com/winman.pdf\fP for more information.
(This format is very similar to the ASCII\[hy]Hex format, but without the ^B
and ^C guard characters.)
.PP
Each data byte is represented as 2 hexadecimal characters,
and is separated by white space from all other data bytes.
.LP
The address for data bytes is set by using a sequence of
\f[CW]$A\fP\f[CI]nnnn\fP\f[CW],\fP characters, where \fInnnn\fP is the
8\[hy]character ascii representation of the address.  The comma is required.
There is no need for an address record unless there are gaps.  Implicitly,
the file starts a address 0 if no address is set before the first
data byte.
.SS Size Multiplier
In general, binary data will expand in sized by approximately 3.0 times
when represented with this format.
.\" ------------------------------------------------------------------------
.br
.ne 2i
.SH EXAMPLE
Here is an example ascii\[hy]hex file.
It contains the data \[lq]Hello, World[rq] to be loaded at address 0x1000.
.RS
.nf
.ft CW
$A1000,
48 65 6C 6C 6F 2C 20 57 6F 72 6C 64 0A
.ft P
.fi
.RE
.\" ------------------------------------------------------------------------
.ds n) srec_cat
.lf 1 ./man/man1/z_copyright.so
.\"
.\"     srecord - manipulate eprom load files
.\"     Copyright (C) 1998, 2006-2009 Peter Miller
.\"
.\"     This program is free software; you can redistribute it and/or modify
.\"     it under the terms of the GNU General Public License as published by
.\"     the Free Software Foundation; either version 3 of the License, or
.\"     (at your option) any later version.
.\"
.\"     This program is distributed in the hope that it will be useful,
.\"     but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"     GNU General Public License for more details.
.\"
.\"     You should have received a copy of the GNU General Public License
.\"     along with this program. If not, see
.\"     <http://www.gnu.org/licenses/>.
.\"
.br
.ne 1i
.SH COPYRIGHT
.lf 1 ./etc/version.so
.ds V) 1.62.D001
.ds v) 1.62
.ds Y) 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013
.lf 23 ./man/man1/z_copyright.so
.I \*(n)
version \*(v)
.br
Copyright
.if n (C)
.if t \(co
\*(Y) Peter Miller
.br
.PP
The
.I \*(n)
program comes with ABSOLUTELY NO WARRANTY;
for details use the '\fI\*(n) \-VERSion License\fP' command.
This is free software
and you are welcome to redistribute it under certain conditions;
for details use the '\fI\*(n) \-VERSion License\fP' command.
.br
.ne 1i
.SH AUTHOR
.TS
tab(;);
l r l.
Peter Miller;E\[hy]Mail:;pmiller@opensource.org.au
/\e/\e*;WWW:;http://miller.emu.id.au/pmiller/
.TE
.lf 61 ./man/man5/srec_needham.5
